# Choose python version
FROM python:3.12-slim

# copy file requirement
COPY requirements.txt .

# install lib
RUN pip install -r requirements.txt

# copy api file
COPY api/main.py .

# mapping port 8000
EXPOSE 8000

# Run the api
CMD ["python", "main.py"]




